[package]
name = "rust-net"
version = "0.1.7"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eval = "0.4.3"
serde = "1.0.130"
serde_json = ">= 0.9, < 2"
tokio = { version = "1.36.0", features = ["full"] }